#!/bin/bash

sink='alsa_output.pci-0000_00_1f.3.analog-stereo'
port=$(pactl list sinks | awk -v s="$sink" '$0~"Name: "s{f=1}f&&/Active Port:/{print $3;exit}')

if [ "$port" = "analog-output-headphones" ]; then 
    pactl set-sink-port "$sink" analog-output-lineout
else 
    pactl set-sink-port "$sink" analog-output-headphones
fi
